name: Main Branch Comprehensive Tests

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  comprehensive-tests:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    name: Run Tests with 2048 Fuzz Runs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Run comprehensive tests
        run: |
          FOUNDRY_PROFILE=main forge test -vv
        env:
          FOUNDRY_PROFILE: main
