name: Test Suite

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format-and-test:
    name: Format Check & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Check formatting
        run: |
          forge --version
          forge fmt --check

      - name: Build
        run: |
          forge build --sizes

      - name: Run tests (PR)
        if: github.event_name == 'pull_request'
        run: |
          forge test -vv
        env:
          FOUNDRY_PROFILE: default

      - name: Run comprehensive tests (Main branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          forge test -vv
        env:
          FOUNDRY_PROFILE: main
